version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:80"
    depends_on:
      - influx
    environment:
      - LOG_LEVEL=DEBUG
      - BUCKET=my-bucket
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=cloud2023
      - INFLUX_URL=http://influx:8086

  influx:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    expose:
      - 8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=cloud2023
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdata:/var/lib/influxdb2

volumes:
  influxdata:
